### PR TITLE
Don't add trailing slash to the base URL

### PR DESCRIPTION
**Pull request by sap1ens**
Currently, it's not possible to provide URLs with additional parameters like `?ssl=true` because of the trailing slash. 

The slash is not needed: baseUrl is primarily used by `ClickHouseUtil.getJdbcUrl`, which [adds it anyway](https://github.com/itinycheng/flink-connector-clickhouse/blob/master/flink-connector-clickhouse/src/main/java/org/apache/flink/connector/clickhouse/util/ClickHouseUtil.java#L35).

### CODE REVIEW

**Comment by czy006** [comment]
Thanks for your contribution, we are currently building work on JDBC version 0.5.0, how about merging this into the 1.16 branch?
cc @sap1ens

**Comment by sap1ens** [comment]
Done! https://github.com/itinycheng/flink-connector-clickhouse/pull/110

**Comment by sap1ens** [comment]
@itinycheng hi! Should I create a new PR or an issue? The problem is still here, I can't use `?ssl=true` in the URL with this connector.

**Comment by itinycheng** [comment]
> @itinycheng hi! Should I create a new PR or an issue? The problem is still here, I can't use `?ssl=true` in the URL with this connector.

Hi @sap1ens 
It seems that the master branch isn't stable for now, we can pay attention to this issue later.

cc @czy006

**Comment by sap1ens** [comment]
Ok, created https://github.com/itinycheng/flink-connector-clickhouse/issues/129

**Pull request closed without merging**
