### PR TITLE
[ISSUE-154] Support Array[Tuple] clickhouse type

### LINKED ISSUE #154: [Bug]:  Flink Logical Type ROW is not supported for Array<Tuple> clickhouse type
### What happened?

Clickhouse connector doesn't support Flink Logical Type ROW when I'm trying to ingest a nested Row into 
Array(Tuple)

```
Caused by: java.lang.UnsupportedOperationException: Unsupported type:ROW<`a` INT, `b` INT, `c` INT>
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:118)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:96)
```

### Affects Versions

master

### What are you seeing the problem on?

_No response_

### How to reproduce

create a clickhouse table with flatten_nested=0 and Array(Tuple) column
```
set flatten_nested=0;
create table test_tuple3(arr Array(Tuple(a Int32, b Int32, c Int32)), z Int32) Engine=MergeTree() Order By tuple();
```

Flink SQL

```
 CREATE TABLE test_tuple (
    arr Array<Row<a int,b int,c int>>,
    z int
  ) WITH (
    'connector' = 'clickhouse',
    'url' = '......',
    'database-name' = 'default',
    'table-name' = 'test_tuple3',
  .....
  );
  insert into test_tuple values(Array[(1,2,3)],600);
```

Got below error:
```
java.lang.UnsupportedOperationException: Unsupported type:ROW<`a` INT, `b` INT, `c` INT>
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:118)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:96)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseRowConverter.lambda$createToExternalConverter$e45b375b$1(ClickHouseRowConverter.java:228)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseRowConverter.toExternal(ClickHouseRowConverter.java:95)
	at org.apache.flink.connector.clickhouse.internal.executor.ClickHouseBatchExecutor.addToBatch(ClickHouseBatchExecutor.java:80)
	at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat.writeRecord(ClickHouseBatchOutputFormat.java:97)
	at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat.writeRecord(ClickHouseBatchOutputFormat.java:33)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.invoke(OutputFormatSinkFunction.java:104)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:50)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:65)
	at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:94)
	at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:75)
	at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39)
	at BatchExecCalc$6.processElement(Unknown Source)
```

### Relevant log output

_No response_

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by qingfei1994**
## Why are the changes needed?

Close #154 .

## Brief change log

- support Row type during serialization and deserialization

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

Test case:
Clickhouse DDL
```
set flatten_nested=0;
create table test_tuple3(arr Array(Tuple(a Int32, b Int32, c Int32)), z Int32) Engine=MergeTree() Order By tuple();
```
Flink SQL
```
 CREATE TABLE test_tuple (
    arr Array<Row<a int,b int,c int>>,
    z int
  ) WITH (
    'connector' = 'clickhouse',
    'url' = '......',
    'database-name' = 'default',
    'table-name' = 'test_tuple3',
  .....
  );
  insert into test_tuple values(Array[(1,2,3)],700);
```

Query result
```
SELECT *
FROM test_tuple3
WHERE z = 700
   ┌─arr───────┬───z─┐
1. │ [(1,2,3)] │ 700 │
   └───────────┴─────┘

1 row in set. Elapsed: 0.004 sec.
```

## Documentation

- Does this pull request introduce a new feature? (yes / no) no
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Review by itinycheng — COMMENTED** [review]
Hi @qingfei1994 

Good PR, but it will be better if it works well with ClickHouseCatalog.
Run the command `./mvnw spotless:apply` before submitting can help us to ensure the code format is correct.

**Comment by qingfei1994** [comment]
> Hi @qingfei1994
> 
> Good PR, but it will be better if it works well with ClickHouseCatalog. Run the command `./mvnw spotless:apply` before submitting can help us to ensure the code format is correct.

Sure I've fix the checkstyle violation, and will also check if it works with ClickhouseCatalog

**Review by czy006 — APPROVED** [review]

**Comment by qingfei1994** [comment]
> > Hi @qingfei1994
> > Good PR, but it will be better if it works well with ClickHouseCatalog. Run the command `./mvnw spotless:apply` before submitting can help us to ensure the code format is correct.
> 
> Sure I've fix the checkstyle violation, and will also check if it works with ClickhouseCatalog

@itinycheng @czy006 
I've tested and fixed the ClickhouseCatalog with Row data type.
Flink SQL:
```
CREATE catalog clickhouse_catalog WITH (
  'type' = 'clickhouse',
  'url' = '.....',
  'database-name' = 'test',
  'username' = '',
  'password' = ''
);

create table print_sink
(
    arr Array<Row<a int,b int, c int>>,
    z int
) with (
'connector'='print'
);

insert into print_sink
select
  arr,
  z
from
  clickhouse_catalog.`default`.test_tuple3;
```
query result:
```
2> +I[[+I[1, 2, 3]], 600]
2> +I[[+I[1, 2, 3]], 600]
2> +I[[+I[4, 5, 6]], 800]
2> +I[[+I[4, 5, 6]], 800]
2> +I[[+I[1, 2, 3]], 700]
```
please  check the latest submitted code.

**Comment by itinycheng** [comment]
Hi @qingfei1994 

I have merged this PR.
One more thing, tuple elements without names are not included in 
the test cases above, like ‘Tuple(T1, T2, ...)’

**Pull request merged**
